// 이모지 목록 — 유니코드 표준 이모지를 emojiall.com의 분류(스마일·사람·동물·음식·활동·여행·
// 사물·기호·깃발)를 따라 묶었다. 그림은 시스템 이모지 글꼴(Segoe UI Emoji)이 그린다.
// 검색어는 한국어·영어 짧은 이름이다. 목록은 자주 쓰는 것 위주로 추린 고정 데이터다.
const emojiData = (() => {
  const G = (id, icon, items) => ({ id, icon, items });
  // items: [이모지, "한글 이름|english name"]
  const GROUPS = [
    G('smileys', '😀', [
      ['😀', '웃음|grinning'], ['😃', '활짝 웃음|smiley'], ['😄', '눈웃음|smile'], ['😁', '씩 웃음|grin'],
      ['😆', '깔깔|laughing'], ['😅', '땀 웃음|sweat smile'], ['🤣', '데굴데굴|rofl'], ['😂', '눈물 웃음|joy'],
      ['🙂', '살짝 웃음|slightly smiling'], ['🙃', '거꾸로|upside down'], ['😉', '윙크|wink'], ['😊', '수줍|blush'],
      ['😇', '천사|innocent'], ['🥰', '사랑에 빠짐|smiling hearts'], ['😍', '하트 눈|heart eyes'], ['🤩', '별 눈|star struck'],
      ['😘', '키스|kissing heart'], ['😗', '뽀뽀|kissing'], ['😚', '눈 감고 뽀뽀|kissing closed eyes'], ['😙', '웃으며 뽀뽀|kissing smiling'],
      ['🥲', '눈물 미소|smiling tear'], ['😋', '맛있다|yum'], ['😛', '메롱|tongue'], ['😜', '윙크 메롱|wink tongue'],
      ['🤪', '정신없음|zany'], ['😝', '눈 감고 메롱|squint tongue'], ['🤑', '돈|money mouth'], ['🤗', '포옹|hugging'],
      ['🤭', '입 가림|hand over mouth'], ['🤫', '쉿|shushing'], ['🤔', '생각|thinking'], ['🤐', '입 지퍼|zipper mouth'],
      ['🤨', '의심|raised eyebrow'], ['😐', '무표정|neutral'], ['😑', '심드렁|expressionless'], ['😶', '입 없음|no mouth'],
      ['😏', '능글|smirk'], ['😒', '시큰둥|unamused'], ['🙄', '눈 굴림|eye roll'], ['😬', '이 드러냄|grimacing'],
      ['🤥', '거짓말|lying'], ['😌', '안도|relieved'], ['😔', '시무룩|pensive'], ['😪', '졸림|sleepy'],
      ['🤤', '침|drooling'], ['😴', '잠|sleeping'], ['😷', '마스크|mask'], ['🤒', '열|thermometer'],
      ['🤕', '붕대|head bandage'], ['🤢', '메스꺼움|nauseated'], ['🤮', '구토|vomiting'], ['🤧', '재채기|sneezing'],
      ['🥵', '더움|hot'], ['🥶', '추움|cold'], ['🥴', '어지러움|woozy'], ['😵', '기절|dizzy'],
      ['🤯', '폭발|exploding head'], ['🤠', '카우보이|cowboy'], ['🥳', '파티|partying'], ['🥸', '변장|disguised'],
      ['😎', '선글라스|sunglasses'], ['🤓', '안경|nerd'], ['🧐', '외눈안경|monocle'], ['😕', '혼란|confused'],
      ['😟', '걱정|worried'], ['🙁', '살짝 찡그림|slightly frowning'], ['☹️', '찡그림|frowning'], ['😮', '놀람|open mouth'],
      ['😯', '헉|hushed'], ['😲', '경악|astonished'], ['😳', '얼굴 붉힘|flushed'], ['🥺', '애원|pleading'],
      ['😦', '입 벌림|frowning open'], ['😧', '고통|anguished'], ['😨', '두려움|fearful'], ['😰', '식은땀|anxious'],
      ['😥', '슬픈 안도|sad relieved'], ['😢', '눈물|crying'], ['😭', '엉엉|loudly crying'], ['😱', '비명|screaming'],
      ['😖', '괴로움|confounded'], ['😣', '끙|persevering'], ['😞', '실망|disappointed'], ['😓', '진땀|downcast sweat'],
      ['😩', '지침|weary'], ['😫', '피곤|tired'], ['🥱', '하품|yawning'], ['😤', '씩씩|triumph'],
      ['😡', '분노|pouting'], ['😠', '화남|angry'], ['🤬', '욕|cursing'], ['😈', '악마 웃음|smiling imp'],
      ['👿', '악마|imp'], ['💀', '해골|skull'], ['☠️', '해적 해골|skull crossbones'], ['💩', '똥|poop'],
      ['🤡', '광대|clown'], ['👹', '도깨비|ogre'], ['👺', '텐구|goblin'], ['👻', '유령|ghost'],
      ['👽', '외계인|alien'], ['👾', '외계 괴물|alien monster'], ['🤖', '로봇|robot'], ['😺', '웃는 고양이|smiling cat'],
      ['😸', '눈웃음 고양이|grinning cat'], ['😹', '웃음 눈물 고양이|joy cat'], ['😻', '하트 눈 고양이|heart eyes cat'], ['😼', '능글 고양이|smirking cat'],
      ['😽', '뽀뽀 고양이|kissing cat'], ['🙀', '놀란 고양이|weary cat'], ['😿', '우는 고양이|crying cat'], ['😾', '화난 고양이|pouting cat'],
      ['❤️', '빨간 하트|red heart'], ['🧡', '주황 하트|orange heart'], ['💛', '노란 하트|yellow heart'], ['💚', '초록 하트|green heart'],
      ['💙', '파란 하트|blue heart'], ['💜', '보라 하트|purple heart'], ['🖤', '검은 하트|black heart'], ['🤍', '흰 하트|white heart'],
      ['🤎', '갈색 하트|brown heart'], ['💔', '깨진 하트|broken heart'], ['❣️', '하트 느낌표|heart exclamation'], ['💕', '두 하트|two hearts'],
      ['💞', '도는 하트|revolving hearts'], ['💓', '뛰는 하트|beating heart'], ['💗', '커지는 하트|growing heart'], ['💖', '반짝 하트|sparkling heart'],
      ['💘', '화살 하트|cupid'], ['💝', '리본 하트|gift heart'], ['💟', '하트 장식|heart decoration'], ['💋', '입술|kiss mark'],
      ['💯', '백점|hundred'], ['💢', '분노 표시|anger'], ['💥', '충돌|collision'], ['💫', '어질|dizzy'],
      ['💦', '땀방울|sweat droplets'], ['💨', '바람|dash'], ['🕳️', '구멍|hole'], ['💬', '말풍선|speech balloon'],
      ['💭', '생각 풍선|thought balloon'], ['💤', '쿨쿨|zzz'],
    ]),
    G('people', '👋', [
      ['👋', '손 흔들기|wave'], ['🤚', '손등|raised back hand'], ['🖐️', '손가락 펼침|hand fingers splayed'], ['✋', '손바닥|raised hand'],
      ['🖖', '벌컨 인사|vulcan'], ['👌', '오케이|ok hand'], ['🤌', '손끝 모음|pinched fingers'], ['🤏', '조금|pinching'],
      ['✌️', '브이|victory'], ['🤞', '손가락 꼬기|crossed fingers'], ['🤟', '사랑해|love you'], ['🤘', '록|rock on'],
      ['🤙', '전화해|call me'], ['👈', '왼쪽|point left'], ['👉', '오른쪽|point right'], ['👆', '위|point up'],
      ['🖕', '가운뎃손가락|middle finger'], ['👇', '아래|point down'], ['☝️', '검지|index up'], ['👍', '좋아요|thumbs up'],
      ['👎', '싫어요|thumbs down'], ['✊', '주먹|fist'], ['👊', '펀치|punch'], ['🤛', '왼쪽 주먹|left fist'],
      ['🤜', '오른쪽 주먹|right fist'], ['👏', '박수|clap'], ['🙌', '만세|raised hands'], ['👐', '손 벌림|open hands'],
      ['🤲', '손 모음|palms up'], ['🤝', '악수|handshake'], ['🙏', '기도|pray'], ['✍️', '쓰기|writing hand'],
      ['💅', '매니큐어|nail polish'], ['🤳', '셀카|selfie'], ['💪', '근육|muscle'], ['🦾', '기계 팔|mechanical arm'],
      ['🦵', '다리|leg'], ['🦶', '발|foot'], ['👂', '귀|ear'], ['👃', '코|nose'],
      ['🧠', '뇌|brain'], ['🫀', '심장|heart organ'], ['🦷', '이|tooth'], ['🦴', '뼈|bone'],
      ['👀', '눈|eyes'], ['👁️', '눈 하나|eye'], ['👅', '혀|tongue'], ['👄', '입|mouth'],
      ['👶', '아기|baby'], ['🧒', '어린이|child'], ['👦', '소년|boy'], ['👧', '소녀|girl'],
      ['🧑', '사람|person'], ['👱', '금발|blond'], ['👨', '남자|man'], ['🧔', '수염|beard'],
      ['👩', '여자|woman'], ['🧓', '노인|older person'], ['👴', '할아버지|old man'], ['👵', '할머니|old woman'],
      ['🙍', '찡그린 사람|frowning person'], ['🙎', '뾰로통|pouting person'], ['🙅', '안 돼|no gesture'], ['🙆', '오케이 동작|ok gesture'],
      ['💁', '안내|tipping hand'], ['🙋', '손 들기|raising hand'], ['🧏', '청각 장애|deaf'], ['🙇', '절|bowing'],
      ['🤦', '얼굴 감싸기|facepalm'], ['🤷', '으쓱|shrug'], ['👮', '경찰|police'], ['🕵️', '탐정|detective'],
      ['💂', '근위병|guard'], ['👷', '건설 노동자|construction worker'], ['🤴', '왕자|prince'], ['👸', '공주|princess'],
      ['👳', '터번|turban'], ['👲', '중국 모자|skullcap'], ['🧕', '히잡|headscarf'], ['🤵', '턱시도|tuxedo'],
      ['👰', '면사포|veil'], ['🤰', '임신|pregnant'], ['🤱', '수유|breast feeding'], ['👼', '아기 천사|angel'],
      ['🎅', '산타|santa'], ['🤶', '산타 부인|mrs claus'], ['🦸', '슈퍼히어로|superhero'], ['🦹', '악당|supervillain'],
      ['🧙', '마법사|mage'], ['🧚', '요정|fairy'], ['🧛', '뱀파이어|vampire'], ['🧜', '인어|merperson'],
      ['🧝', '엘프|elf'], ['🧞', '지니|genie'], ['🧟', '좀비|zombie'], ['💆', '마사지|massage'],
      ['💇', '이발|haircut'], ['🚶', '걷기|walking'], ['🧍', '서 있음|standing'], ['🧎', '무릎|kneeling'],
      ['🏃', '달리기|running'], ['💃', '춤|dancer'], ['🕺', '남자 춤|man dancing'], ['🕴️', '정장 부양|levitating'],
      ['👯', '토끼 귀|bunny ears'], ['🧖', '사우나|sauna'], ['🧗', '암벽|climbing'], ['🤺', '펜싱|fencing'],
      ['🏇', '경마|horse racing'], ['⛷️', '스키|skier'], ['🏂', '스노보드|snowboarder'], ['🏌️', '골프|golfer'],
      ['🏄', '서핑|surfer'], ['🚣', '조정|rowing'], ['🏊', '수영|swimmer'], ['⛹️', '농구|ball'],
      ['🏋️', '역도|weight lifting'], ['🚴', '자전거|bicyclist'], ['🚵', '산악자전거|mountain bike'], ['🤸', '재주넘기|cartwheel'],
      ['🤼', '레슬링|wrestling'], ['🤽', '수구|water polo'], ['🤾', '핸드볼|handball'], ['🤹', '저글링|juggling'],
      ['🧘', '요가|lotus'], ['🛀', '목욕|bath'], ['🛌', '침대|in bed'], ['👭', '여자 둘|women holding hands'],
      ['👫', '남녀|couple'], ['👬', '남자 둘|men holding hands'], ['💏', '키스 커플|kiss'], ['💑', '하트 커플|couple heart'],
      ['👪', '가족|family'], ['🗣️', '말하는 머리|speaking head'], ['👤', '실루엣|bust'], ['👥', '실루엣 둘|busts'],
      ['🫂', '포옹 둘|people hugging'], ['👣', '발자국|footprints'],
    ]),
    G('animals', '🐶', [
      ['🐵', '원숭이 얼굴|monkey face'], ['🐒', '원숭이|monkey'], ['🦍', '고릴라|gorilla'], ['🦧', '오랑우탄|orangutan'],
      ['🐶', '강아지|dog'], ['🐕', '개|dog2'], ['🦮', '안내견|guide dog'], ['🐩', '푸들|poodle'],
      ['🐺', '늑대|wolf'], ['🦊', '여우|fox'], ['🦝', '너구리|raccoon'], ['🐱', '고양이|cat'],
      ['🐈', '고양이 옆모습|cat2'], ['🦁', '사자|lion'], ['🐯', '호랑이|tiger'], ['🐅', '호랑이 옆|tiger2'],
      ['🐆', '표범|leopard'], ['🐴', '말 얼굴|horse face'], ['🐎', '말|horse'], ['🦄', '유니콘|unicorn'],
      ['🦓', '얼룩말|zebra'], ['🦌', '사슴|deer'], ['🐮', '소 얼굴|cow face'], ['🐂', '황소|ox'],
      ['🐃', '물소|water buffalo'], ['🐄', '소|cow'], ['🐷', '돼지 얼굴|pig face'], ['🐖', '돼지|pig'],
      ['🐗', '멧돼지|boar'], ['🐽', '돼지 코|pig nose'], ['🐏', '숫양|ram'], ['🐑', '양|sheep'],
      ['🐐', '염소|goat'], ['🐪', '낙타|camel'], ['🐫', '쌍봉낙타|two hump camel'], ['🦙', '라마|llama'],
      ['🦒', '기린|giraffe'], ['🐘', '코끼리|elephant'], ['🦏', '코뿔소|rhino'], ['🦛', '하마|hippo'],
      ['🐭', '쥐 얼굴|mouse face'], ['🐁', '쥐|mouse'], ['🐀', '시궁쥐|rat'], ['🐹', '햄스터|hamster'],
      ['🐰', '토끼 얼굴|rabbit face'], ['🐇', '토끼|rabbit'], ['🐿️', '다람쥐|chipmunk'], ['🦔', '고슴도치|hedgehog'],
      ['🦇', '박쥐|bat'], ['🐻', '곰|bear'], ['🐨', '코알라|koala'], ['🐼', '판다|panda'],
      ['🦥', '나무늘보|sloth'], ['🦦', '수달|otter'], ['🦨', '스컹크|skunk'], ['🦘', '캥거루|kangaroo'],
      ['🦡', '오소리|badger'], ['🐾', '발자국|paw prints'], ['🦃', '칠면조|turkey'], ['🐔', '닭|chicken'],
      ['🐓', '수탉|rooster'], ['🐣', '부화|hatching chick'], ['🐤', '병아리|baby chick'], ['🐥', '아기 새|front chick'],
      ['🐦', '새|bird'], ['🐧', '펭귄|penguin'], ['🕊️', '비둘기|dove'], ['🦅', '독수리|eagle'],
      ['🦆', '오리|duck'], ['🦢', '백조|swan'], ['🦉', '부엉이|owl'], ['🦩', '플라밍고|flamingo'],
      ['🦚', '공작|peacock'], ['🦜', '앵무새|parrot'], ['🐸', '개구리|frog'], ['🐊', '악어|crocodile'],
      ['🐢', '거북|turtle'], ['🦎', '도마뱀|lizard'], ['🐍', '뱀|snake'], ['🐲', '용 얼굴|dragon face'],
      ['🐉', '용|dragon'], ['🦕', '공룡|sauropod'], ['🦖', '티라노|t-rex'], ['🐳', '고래|whale'],
      ['🐋', '고래 옆|whale2'], ['🐬', '돌고래|dolphin'], ['🦭', '물개|seal'], ['🐟', '물고기|fish'],
      ['🐠', '열대어|tropical fish'], ['🐡', '복어|blowfish'], ['🦈', '상어|shark'], ['🐙', '문어|octopus'],
      ['🐚', '조개|shell'], ['🐌', '달팽이|snail'], ['🦋', '나비|butterfly'], ['🐛', '애벌레|bug'],
      ['🐜', '개미|ant'], ['🐝', '벌|bee'], ['🪲', '딱정벌레|beetle'], ['🐞', '무당벌레|lady beetle'],
      ['🦗', '귀뚜라미|cricket'], ['🕷️', '거미|spider'], ['🕸️', '거미줄|web'], ['🦂', '전갈|scorpion'],
      ['🦟', '모기|mosquito'], ['🦠', '미생물|microbe'], ['💐', '꽃다발|bouquet'], ['🌸', '벚꽃|cherry blossom'],
      ['💮', '흰 꽃|white flower'], ['🏵️', '로제트|rosette'], ['🌹', '장미|rose'], ['🥀', '시든 꽃|wilted'],
      ['🌺', '히비스커스|hibiscus'], ['🌻', '해바라기|sunflower'], ['🌼', '꽃|blossom'], ['🌷', '튤립|tulip'],
      ['🌱', '새싹|seedling'], ['🪴', '화분|potted plant'], ['🌲', '침엽수|evergreen'], ['🌳', '활엽수|tree'],
      ['🌴', '야자수|palm'], ['🌵', '선인장|cactus'], ['🌾', '벼|sheaf'], ['🌿', '허브|herb'],
      ['☘️', '토끼풀|shamrock'], ['🍀', '네잎클로버|four leaf clover'], ['🍁', '단풍|maple'], ['🍂', '낙엽|fallen leaf'],
      ['🍃', '바람 잎|leaf'], ['🍄', '버섯|mushroom'],
    ]),
    G('food', '🍎', [
      ['🍇', '포도|grapes'], ['🍈', '멜론|melon'], ['🍉', '수박|watermelon'], ['🍊', '귤|tangerine'],
      ['🍋', '레몬|lemon'], ['🍌', '바나나|banana'], ['🍍', '파인애플|pineapple'], ['🥭', '망고|mango'],
      ['🍎', '사과|apple'], ['🍏', '풋사과|green apple'], ['🍐', '배|pear'], ['🍑', '복숭아|peach'],
      ['🍒', '체리|cherries'], ['🍓', '딸기|strawberry'], ['🫐', '블루베리|blueberries'], ['🥝', '키위|kiwi'],
      ['🍅', '토마토|tomato'], ['🫒', '올리브|olive'], ['🥥', '코코넛|coconut'], ['🥑', '아보카도|avocado'],
      ['🍆', '가지|eggplant'], ['🥔', '감자|potato'], ['🥕', '당근|carrot'], ['🌽', '옥수수|corn'],
      ['🌶️', '고추|hot pepper'], ['🫑', '피망|bell pepper'], ['🥒', '오이|cucumber'], ['🥬', '잎채소|leafy green'],
      ['🥦', '브로콜리|broccoli'], ['🧄', '마늘|garlic'], ['🧅', '양파|onion'], ['🥜', '땅콩|peanuts'],
      ['🌰', '밤|chestnut'], ['🍞', '빵|bread'], ['🥐', '크루아상|croissant'], ['🥖', '바게트|baguette'],
      ['🫓', '플랫브레드|flatbread'], ['🥨', '프레첼|pretzel'], ['🥯', '베이글|bagel'], ['🥞', '팬케이크|pancakes'],
      ['🧇', '와플|waffle'], ['🧀', '치즈|cheese'], ['🍖', '고기|meat on bone'], ['🍗', '닭다리|poultry leg'],
      ['🥩', '스테이크|cut of meat'], ['🥓', '베이컨|bacon'], ['🍔', '햄버거|hamburger'], ['🍟', '감자튀김|fries'],
      ['🍕', '피자|pizza'], ['🌭', '핫도그|hot dog'], ['🥪', '샌드위치|sandwich'], ['🌮', '타코|taco'],
      ['🌯', '부리토|burrito'], ['🥙', '피타|stuffed flatbread'], ['🧆', '팔라펠|falafel'], ['🥚', '달걀|egg'],
      ['🍳', '프라이|cooking'], ['🥘', '팬 요리|shallow pan'], ['🍲', '찌개|pot of food'], ['🫕', '퐁뒤|fondue'],
      ['🥣', '그릇|bowl with spoon'], ['🥗', '샐러드|salad'], ['🍿', '팝콘|popcorn'], ['🧈', '버터|butter'],
      ['🧂', '소금|salt'], ['🥫', '통조림|canned food'], ['🍱', '도시락|bento'], ['🍘', '센베이|rice cracker'],
      ['🍙', '주먹밥|rice ball'], ['🍚', '밥|rice'], ['🍛', '카레|curry'], ['🍜', '라면|ramen'],
      ['🍝', '스파게티|spaghetti'], ['🍠', '고구마|sweet potato'], ['🍢', '오뎅|oden'], ['🍣', '초밥|sushi'],
      ['🍤', '새우튀김|fried shrimp'], ['🍥', '어묵|fish cake'], ['🥮', '월병|moon cake'], ['🍡', '경단|dango'],
      ['🥟', '만두|dumpling'], ['🥠', '포춘쿠키|fortune cookie'], ['🥡', '테이크아웃|takeout'], ['🦀', '게|crab'],
      ['🦞', '랍스터|lobster'], ['🦐', '새우|shrimp'], ['🦑', '오징어|squid'], ['🦪', '굴|oyster'],
      ['🍦', '소프트아이스크림|soft ice cream'], ['🍧', '빙수|shaved ice'], ['🍨', '아이스크림|ice cream'], ['🍩', '도넛|doughnut'],
      ['🍪', '쿠키|cookie'], ['🎂', '생일 케이크|birthday cake'], ['🍰', '케이크|cake'], ['🧁', '컵케이크|cupcake'],
      ['🥧', '파이|pie'], ['🍫', '초콜릿|chocolate'], ['🍬', '사탕|candy'], ['🍭', '막대사탕|lollipop'],
      ['🍮', '푸딩|custard'], ['🍯', '꿀|honey'], ['🍼', '젖병|baby bottle'], ['🥛', '우유|milk'],
      ['☕', '커피|coffee'], ['🫖', '찻주전자|teapot'], ['🍵', '녹차|tea'], ['🍶', '사케|sake'],
      ['🍾', '샴페인|champagne'], ['🍷', '와인|wine'], ['🍸', '칵테일|cocktail'], ['🍹', '열대 음료|tropical drink'],
      ['🍺', '맥주|beer'], ['🍻', '건배|beers'], ['🥂', '샴페인 건배|clinking glasses'], ['🥃', '위스키|tumbler'],
      ['🥤', '컵 음료|cup with straw'], ['🧋', '버블티|bubble tea'], ['🧃', '주스팩|juice box'], ['🧉', '마테|mate'],
      ['🧊', '얼음|ice'], ['🥢', '젓가락|chopsticks'], ['🍽️', '접시와 식기|plate'], ['🍴', '포크 나이프|fork knife'],
      ['🥄', '숟가락|spoon'], ['🔪', '칼|knife'], ['🏺', '항아리|amphora'],
    ]),
    G('activities', '⚽', [
      ['🎃', '호박등|jack o lantern'], ['🎄', '크리스마스 트리|christmas tree'], ['🎆', '불꽃놀이|fireworks'], ['🎇', '폭죽|sparkler'],
      ['🧨', '폭죽|firecracker'], ['✨', '반짝|sparkles'], ['🎈', '풍선|balloon'], ['🎉', '파티|party popper'],
      ['🎊', '색종이|confetti'], ['🎋', '칠석|tanabata'], ['🎍', '가도마츠|pine decoration'], ['🎎', '히나 인형|dolls'],
      ['🎏', '잉어 깃발|carp streamer'], ['🎐', '풍경|wind chime'], ['🎑', '달맞이|moon viewing'], ['🧧', '홍바오|red envelope'],
      ['🎀', '리본|ribbon'], ['🎁', '선물|gift'], ['🎗️', '리마인더 리본|reminder ribbon'], ['🎟️', '입장권|admission tickets'],
      ['🎫', '티켓|ticket'], ['🎖️', '군 훈장|military medal'], ['🏆', '트로피|trophy'], ['🏅', '메달|medal'],
      ['🥇', '금메달|1st'], ['🥈', '은메달|2nd'], ['🥉', '동메달|3rd'], ['⚽', '축구공|soccer'],
      ['⚾', '야구공|baseball'], ['🥎', '소프트볼|softball'], ['🏀', '농구공|basketball'], ['🏐', '배구공|volleyball'],
      ['🏈', '미식축구|football'], ['🏉', '럭비|rugby'], ['🎾', '테니스|tennis'], ['🥏', '프리스비|flying disc'],
      ['🎳', '볼링|bowling'], ['🏏', '크리켓|cricket game'], ['🏑', '필드하키|field hockey'], ['🏒', '아이스하키|ice hockey'],
      ['🥍', '라크로스|lacrosse'], ['🏓', '탁구|ping pong'], ['🏸', '배드민턴|badminton'], ['🥊', '권투 글러브|boxing glove'],
      ['🥋', '도복|martial arts'], ['🥅', '골대|goal net'], ['⛳', '골프 홀|flag in hole'], ['⛸️', '스케이트|ice skate'],
      ['🎣', '낚시|fishing'], ['🤿', '다이빙 마스크|diving mask'], ['🎽', '러닝 셔츠|running shirt'], ['🎿', '스키|skis'],
      ['🛷', '썰매|sled'], ['🥌', '컬링|curling stone'], ['🎯', '과녁|bullseye'], ['🪀', '요요|yo-yo'],
      ['🪁', '연|kite'], ['🎱', '당구|8 ball'], ['🔮', '수정구슬|crystal ball'], ['🪄', '마술봉|magic wand'],
      ['🧿', '나자르|nazar'], ['🎮', '게임패드|video game'], ['🕹️', '조이스틱|joystick'], ['🎰', '슬롯머신|slot machine'],
      ['🎲', '주사위|dice'], ['🧩', '퍼즐|puzzle'], ['🧸', '곰인형|teddy bear'], ['🪅', '피냐타|pinata'],
      ['🪆', '마트료시카|nesting dolls'], ['♠️', '스페이드|spade'], ['♥️', '하트 카드|heart suit'], ['♦️', '다이아|diamond suit'],
      ['♣️', '클로버|club suit'], ['♟️', '체스 폰|chess pawn'], ['🃏', '조커|joker'], ['🀄', '마작|mahjong'],
      ['🎴', '화투|flower cards'], ['🎭', '연극|performing arts'], ['🖼️', '액자|framed picture'], ['🎨', '팔레트|palette'],
      ['🧵', '실|thread'], ['🪡', '바늘|sewing needle'], ['🧶', '털실|yarn'], ['🪢', '매듭|knot'],
      ['🎼', '악보|musical score'], ['🎵', '음표|musical note'], ['🎶', '음표들|notes'], ['🎙️', '스튜디오 마이크|studio mic'],
      ['🎚️', '레벨 슬라이더|level slider'], ['🎛️', '조절 노브|control knobs'], ['🎤', '마이크|microphone'], ['🎧', '헤드폰|headphone'],
      ['📻', '라디오|radio'], ['🎷', '색소폰|saxophone'], ['🪗', '아코디언|accordion'], ['🎸', '기타|guitar'],
      ['🎹', '피아노|keyboard'], ['🎺', '트럼펫|trumpet'], ['🎻', '바이올린|violin'], ['🪕', '밴조|banjo'],
      ['🥁', '드럼|drum'], ['🪘', '북|long drum'],
    ]),
    G('travel', '🚗', [
      ['🌍', '지구 유럽|globe europe'], ['🌎', '지구 아메리카|globe americas'], ['🌏', '지구 아시아|globe asia'], ['🌐', '지구본|globe meridians'],
      ['🗺️', '세계 지도|world map'], ['🧭', '나침반|compass'], ['🏔️', '설산|snow mountain'], ['⛰️', '산|mountain'],
      ['🌋', '화산|volcano'], ['🗻', '후지산|mount fuji'], ['🏕️', '캠핑|camping'], ['🏖️', '해변|beach'],
      ['🏜️', '사막|desert'], ['🏝️', '무인도|island'], ['🏞️', '국립공원|national park'], ['🏟️', '경기장|stadium'],
      ['🏛️', '고전 건물|classical building'], ['🏗️', '공사|construction'], ['🧱', '벽돌|brick'], ['🏘️', '주택가|houses'],
      ['🏚️', '폐가|derelict house'], ['🏠', '집|house'], ['🏡', '정원 집|house garden'], ['🏢', '사무실|office'],
      ['🏣', '우체국|post office'], ['🏥', '병원|hospital'], ['🏦', '은행|bank'], ['🏨', '호텔|hotel'],
      ['🏪', '편의점|convenience store'], ['🏫', '학교|school'], ['🏬', '백화점|department store'], ['🏭', '공장|factory'],
      ['🏯', '일본 성|japanese castle'], ['🏰', '성|castle'], ['💒', '결혼식|wedding'], ['🗼', '도쿄타워|tokyo tower'],
      ['🗽', '자유의 여신상|statue of liberty'], ['⛪', '교회|church'], ['🕌', '모스크|mosque'], ['🛕', '힌두 사원|hindu temple'],
      ['🕍', '유대교 회당|synagogue'], ['⛩️', '신사|shinto shrine'], ['🕋', '카바|kaaba'], ['⛲', '분수|fountain'],
      ['⛺', '텐트|tent'], ['🌁', '안개|foggy'], ['🌃', '밤 도시|night stars'], ['🏙️', '도시|cityscape'],
      ['🌄', '일출 산|sunrise mountains'], ['🌅', '일출|sunrise'], ['🌆', '황혼 도시|dusk'], ['🌇', '노을|sunset'],
      ['🌉', '밤 다리|bridge night'], ['♨️', '온천|hot springs'], ['🎠', '회전목마|carousel'], ['🎡', '관람차|ferris wheel'],
      ['🎢', '롤러코스터|roller coaster'], ['💈', '이발소|barber'], ['🎪', '서커스|circus'], ['🚂', '증기기관차|locomotive'],
      ['🚃', '객차|railway car'], ['🚄', '고속열차|bullet train'], ['🚅', '신칸센|bullet train nose'], ['🚆', '기차|train'],
      ['🚇', '지하철|metro'], ['🚈', '경전철|light rail'], ['🚉', '역|station'], ['🚊', '트램|tram'],
      ['🚝', '모노레일|monorail'], ['🚞', '산악 철도|mountain railway'], ['🚋', '전차|tram car'], ['🚌', '버스|bus'],
      ['🚍', '오는 버스|oncoming bus'], ['🚎', '트롤리|trolleybus'], ['🚐', '미니버스|minibus'], ['🚑', '구급차|ambulance'],
      ['🚒', '소방차|fire engine'], ['🚓', '경찰차|police car'], ['🚔', '오는 경찰차|oncoming police'], ['🚕', '택시|taxi'],
      ['🚖', '오는 택시|oncoming taxi'], ['🚗', '자동차|car'], ['🚘', '오는 차|oncoming car'], ['🚙', 'SUV|suv'],
      ['🛻', '픽업트럭|pickup'], ['🚚', '트럭|delivery truck'], ['🚛', '대형 트럭|articulated lorry'], ['🚜', '트랙터|tractor'],
      ['🏎️', '경주차|racing car'], ['🏍️', '오토바이|motorcycle'], ['🛵', '스쿠터|motor scooter'], ['🦽', '수동 휠체어|manual wheelchair'],
      ['🦼', '전동 휠체어|motorized wheelchair'], ['🛺', '릭샤|auto rickshaw'], ['🚲', '자전거|bicycle'], ['🛴', '킥보드|kick scooter'],
      ['🛹', '스케이트보드|skateboard'], ['🛼', '롤러스케이트|roller skate'], ['🚏', '버스 정류장|bus stop'], ['🛣️', '고속도로|motorway'],
      ['🛤️', '철길|railway track'], ['🛢️', '기름통|oil drum'], ['⛽', '주유소|fuel pump'], ['🚨', '경광등|police light'],
      ['🚥', '신호등 가로|horizontal traffic light'], ['🚦', '신호등|traffic light'], ['🛑', '정지|stop sign'], ['🚧', '공사 중|construction sign'],
      ['⚓', '닻|anchor'], ['⛵', '요트|sailboat'], ['🛶', '카누|canoe'], ['🚤', '쾌속정|speedboat'],
      ['🛳️', '여객선|passenger ship'], ['⛴️', '페리|ferry'], ['🛥️', '모터보트|motor boat'], ['🚢', '배|ship'],
      ['✈️', '비행기|airplane'], ['🛩️', '경비행기|small airplane'], ['🛫', '이륙|departure'], ['🛬', '착륙|arrival'],
      ['🪂', '낙하산|parachute'], ['💺', '좌석|seat'], ['🚁', '헬리콥터|helicopter'], ['🚟', '현수 철도|suspension railway'],
      ['🚠', '케이블카|mountain cableway'], ['🚡', '곤돌라|aerial tramway'], ['🛰️', '위성|satellite'], ['🚀', '로켓|rocket'],
      ['🛸', 'UFO|flying saucer'], ['🌙', '초승달|crescent moon'], ['🌛', '달 얼굴|first quarter moon face'], ['🌝', '보름달 얼굴|full moon face'],
      ['🌞', '해 얼굴|sun face'], ['⭐', '별|star'], ['🌟', '빛나는 별|glowing star'], ['🌠', '유성|shooting star'],
      ['🌌', '은하수|milky way'], ['☁️', '구름|cloud'], ['⛅', '구름 낀 해|sun behind cloud'], ['⛈️', '천둥 비|thunder'],
      ['🌤️', '해 약간 구름|sun small cloud'], ['🌥️', '해 큰 구름|sun large cloud'], ['🌦️', '해 비|sun rain'], ['🌧️', '비|rain cloud'],
      ['🌨️', '눈|snow cloud'], ['🌩️', '번개 구름|lightning cloud'], ['🌪️', '토네이도|tornado'], ['🌫️', '안개|fog'],
      ['🌬️', '바람 얼굴|wind face'], ['🌀', '태풍|cyclone'], ['🌈', '무지개|rainbow'], ['🌂', '접은 우산|closed umbrella'],
      ['☂️', '우산|umbrella'], ['☔', '비 우산|umbrella rain'], ['⛱️', '파라솔|beach umbrella'], ['⚡', '번개|zap'],
      ['❄️', '눈꽃|snowflake'], ['☃️', '눈사람|snowman'], ['⛄', '눈사람 맑음|snowman without snow'], ['☄️', '혜성|comet'],
      ['🔥', '불|fire'], ['💧', '물방울|droplet'], ['🌊', '파도|wave'],
    ]),
    G('objects', '💡', [
      ['👓', '안경|glasses'], ['🕶️', '선글라스|sunglasses'], ['🥽', '고글|goggles'], ['🥼', '실험복|lab coat'],
      ['🦺', '안전조끼|safety vest'], ['👔', '넥타이|necktie'], ['👕', '티셔츠|t-shirt'], ['👖', '청바지|jeans'],
      ['🧣', '목도리|scarf'], ['🧤', '장갑|gloves'], ['🧥', '코트|coat'], ['🧦', '양말|socks'],
      ['👗', '드레스|dress'], ['👘', '기모노|kimono'], ['🥻', '사리|sari'], ['🩱', '수영복|swimsuit'],
      ['👙', '비키니|bikini'], ['👚', '블라우스|blouse'], ['👛', '지갑|purse'], ['👜', '핸드백|handbag'],
      ['👝', '파우치|pouch'], ['🛍️', '쇼핑백|shopping bags'], ['🎒', '배낭|backpack'], ['👞', '구두|shoe'],
      ['👟', '운동화|sneaker'], ['🥾', '등산화|hiking boot'], ['🥿', '플랫슈즈|flat shoe'], ['👠', '하이힐|high heel'],
      ['👡', '샌들|sandal'], ['🩰', '발레화|ballet shoes'], ['👢', '부츠|boot'], ['👑', '왕관|crown'],
      ['👒', '여성 모자|womans hat'], ['🎩', '실크햇|top hat'], ['🎓', '학사모|graduation cap'], ['🧢', '야구모자|cap'],
      ['⛑️', '구조 헬멧|rescue helmet'], ['📿', '염주|prayer beads'], ['💄', '립스틱|lipstick'], ['💍', '반지|ring'],
      ['💎', '보석|gem'], ['🔇', '음소거|muted'], ['🔈', '스피커|speaker'], ['🔉', '스피커 중간|speaker medium'],
      ['🔊', '스피커 큼|speaker loud'], ['📢', '확성기|loudspeaker'], ['📣', '메가폰|megaphone'], ['📯', '우편 나팔|postal horn'],
      ['🔔', '종|bell'], ['🔕', '종 끔|no bell'], ['📱', '휴대폰|mobile phone'], ['📲', '휴대폰 화살표|phone arrow'],
      ['☎️', '전화기|telephone'], ['📞', '수화기|receiver'], ['📟', '삐삐|pager'], ['📠', '팩스|fax'],
      ['🔋', '배터리|battery'], ['🔌', '플러그|plug'], ['💻', '노트북|laptop'], ['🖥️', '데스크톱|desktop'],
      ['🖨️', '프린터|printer'], ['⌨️', '키보드|keyboard'], ['🖱️', '마우스|mouse'], ['🖲️', '트랙볼|trackball'],
      ['💽', '미니디스크|minidisc'], ['💾', '플로피|floppy'], ['💿', 'CD|cd'], ['📀', 'DVD|dvd'],
      ['🧮', '주판|abacus'], ['🎥', '영화 카메라|movie camera'], ['🎞️', '필름|film frames'], ['📽️', '영사기|projector'],
      ['🎬', '클래퍼|clapper'], ['📺', 'TV|tv'], ['📷', '카메라|camera'], ['📸', '플래시 카메라|camera flash'],
      ['📹', '캠코더|video camera'], ['📼', '비디오테이프|vhs'], ['🔍', '돋보기|magnifier'], ['🔎', '돋보기 오른쪽|magnifier right'],
      ['🕯️', '초|candle'], ['💡', '전구|bulb'], ['🔦', '손전등|flashlight'], ['🏮', '등불|lantern'],
      ['🪔', '기름등|diya'], ['📔', '노트|notebook decorative'], ['📕', '빨간 책|closed book'], ['📖', '펼친 책|open book'],
      ['📗', '초록 책|green book'], ['📘', '파란 책|blue book'], ['📙', '주황 책|orange book'], ['📚', '책들|books'],
      ['📓', '공책|notebook'], ['📒', '장부|ledger'], ['📃', '문서|page curl'], ['📜', '두루마리|scroll'],
      ['📄', '종이|page'], ['📰', '신문|newspaper'], ['🗞️', '말린 신문|rolled newspaper'], ['📑', '책갈피 탭|bookmark tabs'],
      ['🔖', '책갈피|bookmark'], ['🏷️', '라벨|label'], ['💰', '돈주머니|money bag'], ['🪙', '동전|coin'],
      ['💴', '엔|yen'], ['💵', '달러|dollar'], ['💶', '유로|euro'], ['💷', '파운드|pound'],
      ['💸', '날아가는 돈|money wings'], ['💳', '신용카드|credit card'], ['🧾', '영수증|receipt'], ['💹', '상승 차트|chart yen'],
      ['✉️', '봉투|envelope'], ['📧', '이메일|e-mail'], ['📨', '받은 편지|incoming envelope'], ['📩', '보낼 편지|envelope arrow'],
      ['📤', '보내기함|outbox'], ['📥', '받기함|inbox'], ['📦', '소포|package'], ['📫', '우편함|mailbox'],
      ['📮', '우체통|postbox'], ['🗳️', '투표함|ballot box'], ['✏️', '연필|pencil'], ['✒️', '펜촉|black nib'],
      ['🖋️', '만년필|fountain pen'], ['🖊️', '볼펜|pen'], ['🖌️', '붓|paintbrush'], ['🖍️', '크레용|crayon'],
      ['📝', '메모|memo'], ['💼', '서류가방|briefcase'], ['📁', '폴더|file folder'], ['📂', '열린 폴더|open folder'],
      ['🗂️', '카드 색인|card index dividers'], ['📅', '달력|calendar'], ['📆', '떼는 달력|tear off calendar'], ['🗒️', '스프링 노트|spiral notepad'],
      ['🗓️', '스프링 달력|spiral calendar'], ['📇', '명함첩|card index'], ['📈', '상승 그래프|chart up'], ['📉', '하락 그래프|chart down'],
      ['📊', '막대 그래프|bar chart'], ['📋', '클립보드|clipboard'], ['📌', '압정|pushpin'], ['📍', '핀|round pushpin'],
      ['📎', '클립|paperclip'], ['🖇️', '클립 연결|linked paperclips'], ['📏', '자|straight ruler'], ['📐', '삼각자|triangular ruler'],
      ['✂️', '가위|scissors'], ['🗃️', '카드 파일함|card file box'], ['🗄️', '캐비닛|file cabinet'], ['🗑️', '휴지통|wastebasket'],
      ['🔒', '자물쇠|locked'], ['🔓', '열린 자물쇠|unlocked'], ['🔏', '펜 자물쇠|locked pen'], ['🔐', '열쇠 자물쇠|locked key'],
      ['🔑', '열쇠|key'], ['🗝️', '옛 열쇠|old key'], ['🔨', '망치|hammer'], ['🪓', '도끼|axe'],
      ['⛏️', '곡괭이|pick'], ['⚒️', '망치와 곡괭이|hammer pick'], ['🛠️', '망치와 렌치|hammer wrench'], ['🗡️', '단검|dagger'],
      ['⚔️', '검|crossed swords'], ['🔫', '물총|pistol'], ['🪃', '부메랑|boomerang'], ['🏹', '활|bow arrow'],
      ['🛡️', '방패|shield'], ['🪚', '톱|saw'], ['🔧', '렌치|wrench'], ['🪛', '드라이버|screwdriver'],
      ['🔩', '볼트|nut bolt'], ['⚙️', '톱니|gear'], ['🗜️', '바이스|clamp'], ['⚖️', '저울|scale'],
      ['🦯', '흰 지팡이|white cane'], ['🔗', '링크|link'], ['⛓️', '사슬|chains'], ['🪝', '갈고리|hook'],
      ['🧰', '공구함|toolbox'], ['🧲', '자석|magnet'], ['🪜', '사다리|ladder'], ['⚗️', '증류기|alembic'],
      ['🧪', '시험관|test tube'], ['🧫', '배양접시|petri dish'], ['🧬', 'DNA|dna'], ['🔬', '현미경|microscope'],
      ['🔭', '망원경|telescope'], ['📡', '안테나|satellite antenna'], ['💉', '주사기|syringe'], ['🩸', '피|drop of blood'],
      ['💊', '알약|pill'], ['🩹', '반창고|bandage'], ['🩺', '청진기|stethoscope'], ['🚪', '문|door'],
      ['🛗', '엘리베이터|elevator'], ['🪞', '거울|mirror'], ['🪟', '창문|window'], ['🛏️', '침대|bed'],
      ['🛋️', '소파|couch'], ['🪑', '의자|chair'], ['🚽', '변기|toilet'], ['🪠', '뚫어뻥|plunger'],
      ['🚿', '샤워|shower'], ['🛁', '욕조|bathtub'], ['🪤', '쥐덫|mouse trap'], ['🪒', '면도기|razor'],
      ['🧴', '로션|lotion'], ['🧷', '옷핀|safety pin'], ['🧹', '빗자루|broom'], ['🧺', '바구니|basket'],
      ['🧻', '두루마리 휴지|roll of paper'], ['🪣', '양동이|bucket'], ['🧼', '비누|soap'], ['🪥', '칫솔|toothbrush'],
      ['🧽', '스펀지|sponge'], ['🧯', '소화기|fire extinguisher'], ['🛒', '카트|shopping cart'], ['🚬', '담배|cigarette'],
      ['⚰️', '관|coffin'], ['🪦', '묘비|headstone'], ['⚱️', '유골함|urn'], ['🗿', '모아이|moai'],
      ['🪧', '팻말|placard'], ['⌚', '시계|watch'], ['⏰', '알람시계|alarm clock'], ['⏱️', '스톱워치|stopwatch'],
      ['⏲️', '타이머|timer clock'], ['🕰️', '벽시계|mantelpiece clock'], ['⌛', '모래시계|hourglass'], ['⏳', '흐르는 모래시계|hourglass flowing'],
    ]),
    G('symbols', '❤️', [
      ['🏧', 'ATM|atm'], ['🚮', '쓰레기통 표시|litter'], ['🚰', '식수|potable water'], ['♿', '휠체어 표시|wheelchair'],
      ['🚹', '남자 화장실|mens'], ['🚺', '여자 화장실|womens'], ['🚻', '화장실|restroom'], ['🚼', '유아|baby symbol'],
      ['🚾', 'WC|water closet'], ['🛂', '여권 심사|passport control'], ['🛃', '세관|customs'], ['🛄', '수하물|baggage claim'],
      ['🛅', '보관소|left luggage'], ['⚠️', '경고|warning'], ['🚸', '어린이 보호|children crossing'], ['⛔', '진입 금지|no entry'],
      ['🚫', '금지|prohibited'], ['🚳', '자전거 금지|no bicycles'], ['🚭', '금연|no smoking'], ['🚯', '투기 금지|no littering'],
      ['🚱', '비식수|non potable'], ['🚷', '보행 금지|no pedestrians'], ['📵', '휴대폰 금지|no phones'], ['🔞', '18금|underage'],
      ['☢️', '방사능|radioactive'], ['☣️', '생물 위험|biohazard'], ['⬆️', '위 화살표|up arrow'], ['↗️', '오른쪽 위|up right'],
      ['➡️', '오른쪽 화살표|right arrow'], ['↘️', '오른쪽 아래|down right'], ['⬇️', '아래 화살표|down arrow'], ['↙️', '왼쪽 아래|down left'],
      ['⬅️', '왼쪽 화살표|left arrow'], ['↖️', '왼쪽 위|up left'], ['↕️', '상하|up down'], ['↔️', '좌우|left right'],
      ['↩️', '되돌리기|return left'], ['↪️', '앞으로|return right'], ['⤴️', '위로 꺾임|curve up'], ['⤵️', '아래로 꺾임|curve down'],
      ['🔃', '시계 방향|clockwise'], ['🔄', '반시계|counterclockwise'], ['🔙', '뒤로|back'], ['🔚', '끝|end'],
      ['🔛', '켜짐|on'], ['🔜', '곧|soon'], ['🔝', '맨 위|top'], ['🛐', '예배|place of worship'],
      ['⚛️', '원자|atom'], ['🕉️', '옴|om'], ['✡️', '다윗의 별|star of david'], ['☸️', '법륜|wheel of dharma'],
      ['☯️', '음양|yin yang'], ['✝️', '십자가|cross'], ['☦️', '정교회 십자가|orthodox cross'], ['☪️', '별과 초승달|star crescent'],
      ['☮️', '평화|peace'], ['🕎', '메노라|menorah'], ['🔯', '육각별|six pointed star'], ['♈', '양자리|aries'],
      ['♉', '황소자리|taurus'], ['♊', '쌍둥이자리|gemini'], ['♋', '게자리|cancer'], ['♌', '사자자리|leo'],
      ['♍', '처녀자리|virgo'], ['♎', '천칭자리|libra'], ['♏', '전갈자리|scorpio'], ['♐', '궁수자리|sagittarius'],
      ['♑', '염소자리|capricorn'], ['♒', '물병자리|aquarius'], ['♓', '물고기자리|pisces'], ['⛎', '뱀주인자리|ophiuchus'],
      ['🔀', '셔플|shuffle'], ['🔁', '반복|repeat'], ['🔂', '한 곡 반복|repeat one'], ['▶️', '재생|play'],
      ['⏩', '빨리감기|fast forward'], ['⏭️', '다음 트랙|next track'], ['⏯️', '재생/일시정지|play pause'], ['◀️', '되감기|reverse'],
      ['⏪', '빨리 되감기|rewind'], ['⏮️', '이전 트랙|previous track'], ['🔼', '위 버튼|up button'], ['⏫', '빠른 위|fast up'],
      ['🔽', '아래 버튼|down button'], ['⏬', '빠른 아래|fast down'], ['⏸️', '일시정지|pause'], ['⏹️', '정지|stop'],
      ['⏺️', '녹화|record'], ['⏏️', '꺼내기|eject'], ['🎦', '영화관|cinema'], ['🔅', '어둡게|dim'],
      ['🔆', '밝게|bright'], ['📶', '안테나 신호|antenna bars'], ['📳', '진동|vibration'], ['📴', '전원 끔|phone off'],
      ['♀️', '여성|female'], ['♂️', '남성|male'], ['⚧️', '트랜스젠더|transgender'], ['✖️', '곱하기|multiply'],
      ['➕', '더하기|plus'], ['➖', '빼기|minus'], ['➗', '나누기|divide'], ['♾️', '무한|infinity'],
      ['‼️', '느낌표 둘|double exclamation'], ['⁉️', '느낌표 물음표|exclamation question'], ['❓', '물음표|question'], ['❔', '흰 물음표|white question'],
      ['❕', '흰 느낌표|white exclamation'], ['❗', '느낌표|exclamation'], ['〰️', '물결선|wavy dash'], ['💱', '환전|currency exchange'],
      ['💲', '달러 기호|dollar sign'], ['⚕️', '의료|medical'], ['♻️', '재활용|recycle'], ['⚜️', '백합 문장|fleur de lis'],
      ['🔱', '삼지창|trident'], ['📛', '이름표|name badge'], ['🔰', '초보|beginner'], ['⭕', '동그라미|circle'],
      ['✅', '체크 상자|check mark button'], ['☑️', '체크 표시|ballot check'], ['✔️', '체크|check mark'], ['❌', '엑스|cross mark'],
      ['❎', '엑스 상자|cross mark button'], ['➰', '고리|curly loop'], ['➿', '이중 고리|double curly loop'], ['〽️', '부분 교체|part alternation'],
      ['✳️', '팔각 별표|eight spoked asterisk'], ['✴️', '팔각별|eight pointed star'], ['❇️', '반짝임|sparkle'], ['©️', '저작권|copyright'],
      ['®️', '등록 상표|registered'], ['™️', '상표|trademark'], ['#️⃣', '샵|hash'], ['*️⃣', '별표|asterisk'],
      ['0️⃣', '0|zero'], ['1️⃣', '1|one'], ['2️⃣', '2|two'], ['3️⃣', '3|three'],
      ['4️⃣', '4|four'], ['5️⃣', '5|five'], ['6️⃣', '6|six'], ['7️⃣', '7|seven'],
      ['8️⃣', '8|eight'], ['9️⃣', '9|nine'], ['🔟', '10|ten'], ['🔠', '대문자|capital letters'],
      ['🔡', '소문자|lowercase'], ['🔢', '숫자|numbers'], ['🔣', '기호|symbols'], ['🔤', '알파벳|abc'],
      ['🅰️', 'A형|a button'], ['🆎', 'AB형|ab button'], ['🅱️', 'B형|b button'], ['🆑', 'CL|cl'],
      ['🆒', 'COOL|cool'], ['🆓', 'FREE|free'], ['ℹ️', '정보|information'], ['🆔', 'ID|id'],
      ['Ⓜ️', 'M 원|circled m'], ['🆕', 'NEW|new'], ['🆖', 'NG|ng'], ['🅾️', 'O형|o button'],
      ['🆗', 'OK|ok'], ['🅿️', '주차|parking'], ['🆘', 'SOS|sos'], ['🆙', 'UP|up'],
      ['🆚', 'VS|vs'], ['🈁', '여기|koko'], ['🈂️', '서비스|sa'], ['🈷️', '월|monthly'],
      ['🈶', '유료|not free'], ['🈯', '지정|reserved'], ['🉐', '득|bargain'], ['🈹', '할인|discount'],
      ['🈚', '무료|free of charge'], ['🈲', '금지|prohibited ja'], ['🉑', '가능|acceptable'], ['🈸', '신청|application'],
      ['🈴', '합격|passing'], ['🈳', '빈방|vacancy'], ['㊗️', '축하|congratulations'], ['㊙️', '비밀|secret'],
      ['🈺', '영업 중|open for business'], ['🈵', '만석|no vacancy'], ['🔴', '빨간 원|red circle'], ['🟠', '주황 원|orange circle'],
      ['🟡', '노란 원|yellow circle'], ['🟢', '초록 원|green circle'], ['🔵', '파란 원|blue circle'], ['🟣', '보라 원|purple circle'],
      ['🟤', '갈색 원|brown circle'], ['⚫', '검은 원|black circle'], ['⚪', '흰 원|white circle'], ['🟥', '빨간 네모|red square'],
      ['🟧', '주황 네모|orange square'], ['🟨', '노란 네모|yellow square'], ['🟩', '초록 네모|green square'], ['🟦', '파란 네모|blue square'],
      ['🟪', '보라 네모|purple square'], ['🟫', '갈색 네모|brown square'], ['⬛', '검은 네모|black square'], ['⬜', '흰 네모|white square'],
      ['◼️', '중간 검은 네모|black medium square'], ['◻️', '중간 흰 네모|white medium square'], ['🔶', '주황 마름모|orange diamond'], ['🔷', '파란 마름모|blue diamond'],
      ['🔸', '작은 주황 마름모|small orange diamond'], ['🔹', '작은 파란 마름모|small blue diamond'], ['🔺', '빨간 삼각형|red triangle up'], ['🔻', '아래 빨간 삼각형|red triangle down'],
      ['💠', '다이아 점|diamond with dot'], ['🔘', '라디오 버튼|radio button'], ['🔳', '흰 네모 버튼|white square button'], ['🔲', '검은 네모 버튼|black square button'],
    ]),
    G('flags', '🏁', [
      ['🏁', '체커 깃발|chequered flag'], ['🚩', '삼각 깃발|triangular flag'], ['🎌', '교차 깃발|crossed flags'], ['🏴', '검은 깃발|black flag'],
      ['🏳️', '흰 깃발|white flag'], ['🏳️‍🌈', '무지개 깃발|rainbow flag'], ['🏴‍☠️', '해적 깃발|pirate flag'], ['🇰🇷', '한국|korea'],
      ['🇺🇸', '미국|usa'], ['🇯🇵', '일본|japan'], ['🇨🇳', '중국|china'], ['🇬🇧', '영국|uk'],
      ['🇫🇷', '프랑스|france'], ['🇩🇪', '독일|germany'], ['🇮🇹', '이탈리아|italy'], ['🇪🇸', '스페인|spain'],
      ['🇨🇦', '캐나다|canada'], ['🇦🇺', '호주|australia'], ['🇧🇷', '브라질|brazil'], ['🇮🇳', '인도|india'],
      ['🇷🇺', '러시아|russia'], ['🇻🇳', '베트남|vietnam'], ['🇹🇭', '태국|thailand'], ['🇸🇬', '싱가포르|singapore'],
      ['🇹🇼', '대만|taiwan'], ['🇭🇰', '홍콩|hong kong'], ['🇵🇭', '필리핀|philippines'], ['🇮🇩', '인도네시아|indonesia'],
      ['🇲🇾', '말레이시아|malaysia'], ['🇲🇽', '멕시코|mexico'], ['🇳🇱', '네덜란드|netherlands'], ['🇸🇪', '스웨덴|sweden'],
      ['🇨🇭', '스위스|switzerland'], ['🇹🇷', '튀르키예|turkey'], ['🇦🇪', 'UAE|uae'], ['🇺🇳', 'UN|united nations'],
    ]),
  ];
  return {
    groups: () => GROUPS,
    // 검색: 한글·영어 이름에 부분 일치
    search(q) {
      const n = (q || '').trim().toLowerCase();
      if (!n) return [];
      const out = [];
      for (const g of GROUPS)
        for (const it of g.items)
          if (it[1].toLowerCase().includes(n)) out.push(it);
      return out;
    },
  };
})();
